// Code generated by go-swagger; DO NOT EDIT.

package authors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddAuthorHandlerFunc turns a function with the right signature into a add author handler
type AddAuthorHandlerFunc func(AddAuthorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddAuthorHandlerFunc) Handle(params AddAuthorParams) middleware.Responder {
	return fn(params)
}

// AddAuthorHandler interface for that can handle valid add author params
type AddAuthorHandler interface {
	Handle(AddAuthorParams) middleware.Responder
}

// NewAddAuthor creates a new http.Handler for the add author operation
func NewAddAuthor(ctx *middleware.Context, handler AddAuthorHandler) *AddAuthor {
	return &AddAuthor{Context: ctx, Handler: handler}
}

/*
	AddAuthor swagger:route POST /authors Authors addAuthor

Add a new author to the store
*/
type AddAuthor struct {
	Context *middleware.Context
	Handler AddAuthorHandler
}

func (o *AddAuthor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddAuthorParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// AddAuthorCreatedBody add author created body
//
// swagger:model AddAuthorCreatedBody
type AddAuthorCreatedBody struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this add author created body
func (o *AddAuthorCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this add author created body based on context it is used
func (o *AddAuthorCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AddAuthorCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddAuthorCreatedBody) UnmarshalBinary(b []byte) error {
	var res AddAuthorCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
