// Code generated by go-swagger; DO NOT EDIT.

package authors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteAuthorCreatedCode is the HTTP code returned for type DeleteAuthorCreated
const DeleteAuthorCreatedCode int = 201

/*
DeleteAuthorCreated Deleted

swagger:response deleteAuthorCreated
*/
type DeleteAuthorCreated struct {

	/*
	  In: Body
	*/
	Payload *DeleteAuthorCreatedBody `json:"body,omitempty"`
}

// NewDeleteAuthorCreated creates DeleteAuthorCreated with default headers values
func NewDeleteAuthorCreated() *DeleteAuthorCreated {

	return &DeleteAuthorCreated{}
}

// WithPayload adds the payload to the delete author created response
func (o *DeleteAuthorCreated) WithPayload(payload *DeleteAuthorCreatedBody) *DeleteAuthorCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete author created response
func (o *DeleteAuthorCreated) SetPayload(payload *DeleteAuthorCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAuthorCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAuthorBadRequestCode is the HTTP code returned for type DeleteAuthorBadRequest
const DeleteAuthorBadRequestCode int = 400

/*
DeleteAuthorBadRequest Invalid ID supplied

swagger:response deleteAuthorBadRequest
*/
type DeleteAuthorBadRequest struct {
}

// NewDeleteAuthorBadRequest creates DeleteAuthorBadRequest with default headers values
func NewDeleteAuthorBadRequest() *DeleteAuthorBadRequest {

	return &DeleteAuthorBadRequest{}
}

// WriteResponse to the client
func (o *DeleteAuthorBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteAuthorNotFoundCode is the HTTP code returned for type DeleteAuthorNotFound
const DeleteAuthorNotFoundCode int = 404

/*
DeleteAuthorNotFound Author not found

swagger:response deleteAuthorNotFound
*/
type DeleteAuthorNotFound struct {
}

// NewDeleteAuthorNotFound creates DeleteAuthorNotFound with default headers values
func NewDeleteAuthorNotFound() *DeleteAuthorNotFound {

	return &DeleteAuthorNotFound{}
}

// WriteResponse to the client
func (o *DeleteAuthorNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
