// Code generated by go-swagger; DO NOT EDIT.

package authors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAuthorHandlerFunc turns a function with the right signature into a delete author handler
type DeleteAuthorHandlerFunc func(DeleteAuthorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAuthorHandlerFunc) Handle(params DeleteAuthorParams) middleware.Responder {
	return fn(params)
}

// DeleteAuthorHandler interface for that can handle valid delete author params
type DeleteAuthorHandler interface {
	Handle(DeleteAuthorParams) middleware.Responder
}

// NewDeleteAuthor creates a new http.Handler for the delete author operation
func NewDeleteAuthor(ctx *middleware.Context, handler DeleteAuthorHandler) *DeleteAuthor {
	return &DeleteAuthor{Context: ctx, Handler: handler}
}

/*
	DeleteAuthor swagger:route DELETE /authors/{authorId} Authors deleteAuthor

Deletes an author
*/
type DeleteAuthor struct {
	Context *middleware.Context
	Handler DeleteAuthorHandler
}

func (o *DeleteAuthor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteAuthorParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
