// Code generated by go-swagger; DO NOT EDIT.

package authors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteAuthorParams creates a new DeleteAuthorParams object
//
// There are no default values defined in the spec.
func NewDeleteAuthorParams() DeleteAuthorParams {

	return DeleteAuthorParams{}
}

// DeleteAuthorParams contains all the bound params for the delete author operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteAuthor
type DeleteAuthorParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID author to delete
	  Required: true
	  In: path
	*/
	AuthorID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteAuthorParams() beforehand.
func (o *DeleteAuthorParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAuthorID, rhkAuthorID, _ := route.Params.GetOK("authorId")
	if err := o.bindAuthorID(rAuthorID, rhkAuthorID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAuthorID binds and validates parameter AuthorID from path.
func (o *DeleteAuthorParams) bindAuthorID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("authorId", "path", "int64", raw)
	}
	o.AuthorID = value

	return nil
}
