// Code generated by go-swagger; DO NOT EDIT.

package authors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAuthorByIDHandlerFunc turns a function with the right signature into a get author by Id handler
type GetAuthorByIDHandlerFunc func(GetAuthorByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthorByIDHandlerFunc) Handle(params GetAuthorByIDParams) middleware.Responder {
	return fn(params)
}

// GetAuthorByIDHandler interface for that can handle valid get author by Id params
type GetAuthorByIDHandler interface {
	Handle(GetAuthorByIDParams) middleware.Responder
}

// NewGetAuthorByID creates a new http.Handler for the get author by Id operation
func NewGetAuthorByID(ctx *middleware.Context, handler GetAuthorByIDHandler) *GetAuthorByID {
	return &GetAuthorByID{Context: ctx, Handler: handler}
}

/*
	GetAuthorByID swagger:route GET /authors/{authorId} Authors getAuthorById

# Find author by ID

Returns a single author
*/
type GetAuthorByID struct {
	Context *middleware.Context
	Handler GetAuthorByIDHandler
}

func (o *GetAuthorByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuthorByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAuthorByIDBadRequestBody get author by ID bad request body
//
// swagger:model GetAuthorByIDBadRequestBody
type GetAuthorByIDBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get author by ID bad request body
func (o *GetAuthorByIDBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get author by ID bad request body based on context it is used
func (o *GetAuthorByIDBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAuthorByIDBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAuthorByIDBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetAuthorByIDBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetAuthorByIDNotFoundBody get author by ID not found body
//
// swagger:model GetAuthorByIDNotFoundBody
type GetAuthorByIDNotFoundBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get author by ID not found body
func (o *GetAuthorByIDNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get author by ID not found body based on context it is used
func (o *GetAuthorByIDNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAuthorByIDNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAuthorByIDNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetAuthorByIDNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
