// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Book authors
//
//	This is server about authors
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
